stages:
    data_ingestion:
            cmd: python src/pipeline/stage_01_data_ingestion.py
            deps:
                - src/pipeline/stage_01_data_ingestion.py
                - params.yaml
            params:
                - data_ingestion.root_dir
                - data_ingestion.source_URL
                - data_ingestion.local_data_file
                - data_ingestion.unzip_dir
            outs:
                - artifacts/data_ingestion/data/