artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL:   https://github.com/GregaVrbancic/Phishing-Dataset/blob/master/dataset_full.csv
  local_data_file: artifacts/data_ingestion/data.csv
  unzip_dir: artifact/data_ingestion
  