artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL:   https://raw.githubusercontent.com/GregaVrbancic/Phishing-Dataset/master/dataset_full.csv
  local_data_file: artifacts/data_ingestion/data/data.csv
  unzip_dir: artifact/data_ingestion
  ingected_train_dir: artifact/data_ingestion/ingected_data/ingected_train_dir
  ingected_test_dir: artifact/data_ingestion/ingected_data/ingected_test_dir
  